### ISSUE TITLE
Screen is cut off on Windows (exe file)

### ISSUE THREAD

**Issue by pdjan** [melvinchia3636/Youtube-Video-Downloader-GUI#1]
Hi, first issue from me :)

When I run exe file on Windows 8.1 screen is cut off. Window is not resizable and app is not usable.

![bug](https://user-images.githubusercontent.com/45166426/82726719-3c854700-9ce6-11ea-82a4-7b7a683f61ff.png)

**Comment by melvinchia3636** [comment]
> Hi, first issue from me :)
> 
> When I run exe file on Windows 8.1 screen is cut off. Window is not resizable and app is not usable.
> 
> ![bug](https://user-images.githubusercontent.com/45166426/82726719-3c854700-9ce6-11ea-82a4-7b7a683f61ff.png)

new version executable file is now downloadable using the link in readme.md
